# Generated by Django 6.0.1 on 2026-01-11 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('social', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('automation_type', models.CharField(choices=[('auto_reply', 'Auto Reply'), ('scheduled_post', 'Scheduled Post'), ('engagement', 'Engagement')], max_length=50)),
                ('target', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('interval_minutes', models.IntegerField(default=60)),
                ('daily_limit', models.IntegerField(default=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed')], default='active', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('social_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to='social.socialaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Automation Rule',
                'verbose_name_plural': 'Automation Rules',
                'db_table': 'automations_automationrule',
            },
        ),
    ]
