# Generated by Django 6.0.1 on 2026-01-11 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('followers', models.IntegerField(default=0)),
                ('following', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('shares', models.IntegerField(default=0)),
                ('impressions', models.IntegerField(default=0)),
                ('reach', models.IntegerField(default=0)),
                ('profile_views', models.IntegerField(default=0)),
                ('website_clicks', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('social_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='social.socialaccount')),
            ],
            options={
                'verbose_name': 'Analytics Data',
                'verbose_name_plural': 'Analytics Data',
                'db_table': 'analytics_analyticsdata',
                'ordering': ['-date'],
                'unique_together': {('social_account', 'date')},
            },
        ),
    ]
