// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ksdbqbnojqtsvbqzrixa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtzZGJxYm5vanF0c3ZicXpyaXhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1NTA3MzQsImV4cCI6MjA3MzEyNjczNH0.2wro20zSj1vZ5KJ1Z7LE9-KYg7SPayUkcRKwbWF_CoI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});